### ISSUE TITLE
Novas consultas de relacionamentos de endPoints

### ISSUE THREAD

**Issue by IgorGabrielM** [nailtonvital/study-space#6]
- [x] Listar os posts do usuário pelo id
 - [x] O comments count nn ta funcionando
 - [x] No find do user nn ta trazendo os posts que ele já fez
 - [x] No post que esta dentro do interest tem que trazer o user
 - [x] Trazer o id do usário no jwt
 - [ ] Ver a possibilidade de implementar o base64 no imageUrl do post

**Comment by nailtonvital** [comment]
Somente não foi possível colocar como base 64 a propriedade da URL da imagem
